# WebSocket event names
AUTH_CONNECTED = "auth:connected"
ROOM_CREATE = "room:create"
ROOM_CREATED = "room:created"
ROOM_JOIN = "room:join"
ROOM_JOINED = "room:joined"
ROOM_LEAVE = "room:leave"
ROOM_STATUS = "room:status"
ROOM_RECONNECT = "room:reconnect"
GAME_START = "game:start"
GAME_MOVE = "game:move"
GAME_MOVE_REJECTED = "game:move_rejected"
GAME_RESIGN = "game:resign"
GAME_DRAW_OFFER = "game:draw_offer"
GAME_DRAW_RESPONSE = "game:draw_response"
GAME_END = "game:end"
CHAT_SEND = "chat:send"
CHAT_RECEIVE = "chat:receive"
CHAT_TYPING = "chat:typing"
REACTION_ADD = "reaction:add"
REACTION_UPDATE = "reaction:update"
USER_ONLINE = "user:online"
USER_OFFLINE = "user:offline"
ERROR = "error"

INIT_GAME = "init_game"
MOVE = "move"
GAME_OVER = "game_over"
